### PR TITLE
Fix/no firstframetime

### LINKED ISSUE #362: Start time can't be larger than zero
## Description
If a trajectory starts at a time value larger than zero, time playback controls other than 'play' don't work.

## Expected Behavior
Time controls should work no matter what time the simulation starts at

## Reproduction
A version of the same trajectory when [time starts at zero](https://staging.simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/time_starts_at_zero.simularium) and when [time starts larger than zero](https://staging.simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/time_starts_after_zero.simularium). 

1. load the trajectory with time larger than zero
2. click or drag the time bar to skip to a time with or without hitting play first
3. the time bar is frozen with spinners on all the buttons

## Environment
prod or staging, Firefox

### PR DESCRIPTION
**Pull request by interim17**
Time Estimate or Size
=======
_small_

Problem
=======
Closes #362 

Solution
========
Recent changes to octopus and this @ascibisz [PR from yesterday](https://github.com/simularium/octopus/pull/82) seem to have mostly resolved these bugs. We don't need to subtract firstFrameTime anymore, when calling `goToRemoteSimulationTime` and so `visData.firstFrameTime` isn't being used anywhere. I just removed all reference to it. The front end gets the correct `firstFrameTime` by reading the `timeData` when the trajectory lands, we dont need to store it in the viewer.

Prior to realizing Alli had already fixed this I wrote code that I think improves on how we were storing `firstFrameTime` if we want it later, but for now I think we can just remove it

Start time of 0 was hard coded into the test bed slider. I changed it to act more like the website and get the value from `timeData` on initial play.

Steps to Verify:
----------------
1. Install viewer in website
1. Try all the playback controls for the trajectories linked in the issue without hitting play first and see if you get hung up on anything and if first frame time displays correctly.

### CODE REVIEW

File: examples/src/Viewer.tsx [hunk 1]
```diff
@@ -412,6 +416,7 @@ class Viewer extends React.Component<InputParams, ViewerState> {
         // if (!fileName.includes(".simularium")) {
         //     return new
         // }
```
Comment (meganrm) [inline examples/src/Viewer.tsx:418]: I know it's not part of this code, but could this commented out code be removed ?

**Review by meganrm — APPROVED** [review]

File: examples/src/Viewer.tsx (hunk 1 above)
Comment (interim17) [reply examples/src/Viewer.tsx]: sure :)

**Review by frasercl — APPROVED** [review]
